version: '3.0'
services:
  inwealth-api:
    build: ./inwlth-api
    image: inwlth-api
    container_name: inwlth-api
    restart: unless-stopped
    volumes:
      - ./inwlth-api:/app
      -  inwlth-back_node-modules:/app/node_modules
      - node14-alpine_npm-cache:/root/.npm
    ports:
      - "3000:3000"
    networks:
      - inwlth-dev

  nginx:
    build: ./nginx
    image: inwlth-nginx
    container_name: inwlth-nginx
    restart: unless-stopped
    depends_on:
      - inwlth-api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inwlth-dev

networks:
  inwealth-dev:
    driver: bridge

volumes:
  inwealth-back_node-modules:
  node14-alpine_npm-cache:
